Vagrant.configure("2") do |config|
  config.vm.define "gitlab-ce" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.hostname = 'gitlab-ce'
    vm1.vm.box_url = "centos/7"
    config.vm.network :private_network, ip: "33.33.33.33"
    config.vm.network :forwarded_port, guest: 80, host: 8080
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "centos/7"
    vm2.vm.hostname = 'vm2'
    vm2.vm.box_url = "centos/7"
    vm2.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", auto_config: false
  end

end