Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.box_check_update = false
    config.vm.hostname = "ansible-master"
    config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
       vb.gui = false
       vb.memory = "2048"
       vb.cpus = 2
    end
    config.vm.provision "shell", path: "ansible-setup.sh"
  end